name: Docker
on: push
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . -f Dockerfile -t buildessential/debian --build-arg BASE_IMAGE=debian:buster-slim
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username buildessential --password-stdin
      - name: Push image to Docker Hub
        run: docker push buildessential/debian
