name: Docker
on:
  push:
  schedule:
    - cron: '41 01 * * *'
jobs:
  build:
    name: "${{ matrix.name }}"
    strategy:
      matrix:
        name: [Debian Bullseye, Debian Bookworm, Ubuntu Focal, Ubuntu Jammy, Ubuntu Noble]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set variables
        run: |
          read -ra arr <<< "${{ matrix.name }}"
          OS="$(tr '[:upper:]' '[:lower:]' <<< "${arr[0]}")"
          RELEASE="$(tr '[:upper:]' '[:lower:]' <<< "${arr[1]}")"
          BASE_IMAGE="$OS:$(test "$OS" = "debian" && echo "$RELEASE-slim" || echo "$RELEASE")"
          echo "OS=$OS" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username buildessential --password-stdin
      - name: Check if (re)build is required
        run: |
          REBUILD=0
          if docker pull "buildessential/$OS:$RELEASE"; then
            docker pull "$BASE_IMAGE"
            BASE_LAYERS="$(docker image inspect --format '{{range .RootFS.Layers}}{{.}};{{end}}' "$BASE_IMAGE")"
            EXISTING_LAYERS="$(docker image inspect --format '{{range .RootFS.Layers}}{{.}};{{end}}' "buildessential/$OS:$RELEASE")"
            # If the latest existing image is not based on the latest base image, we need to rebuild
            [[ "$EXISTING_LAYERS" = "$BASE_LAYERS"* ]] || REBUILD=1
          else
            # If the image does not yet exist, we need to rebuild, or rather build for the first time!
            REBUILD=1
          fi
          [[ "$REBUILD" = 1 ]] && echo "Rebuild required" || echo "Rebuild not required"
          echo "REBUILD=$REBUILD" >> $GITHUB_ENV
      - name: Build image
        if: ${{ env.REBUILD == 1 }}
        run: |
          docker build . -f Dockerfile -t "buildessential/$OS:$RELEASE" --build-arg "BASE_IMAGE=$BASE_IMAGE"
      - name: Push image to Docker Hub
        if: ${{ env.REBUILD == 1 }}
        run: |
          docker push "buildessential/$OS:$RELEASE"
          if [ "$RELEASE" = "buster" ] || [ "$RELEASE" = "focal" ]; then
            docker tag "buildessential/$OS:$RELEASE" "buildessential/$OS:latest"
            docker push "buildessential/$OS:latest"
          fi
