name: Docker
on: push
jobs:
  build:
    name: "${{ matrix.name }}"
    strategy:
      matrix:
        name: [Debian Stretch, Debian Buster, Ubuntu Xenial, Ubuntu Bionic, Ubuntu Focal, Ubuntu Groovy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        run: |
          read -ra arr <<< "${{ matrix.name }}"
          OS="$(tr '[:upper:]' '[:lower:]' <<< "${arr[0]}")"
          RELEASE="$(tr '[:upper:]' '[:lower:]' <<< "${arr[1]}")"
          BASE_IMAGE="$OS:$(test "$OS" = "debian" && echo "$RELEASE-slim" || echo "$RELEASE")"
          echo "OS=$OS" >> $GITHUB_ENV
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_ENV
      - name: Build image
        run: |
          docker build . -f Dockerfile -t "buildessential/$OS:$RELEASE" --build-arg "BASE_IMAGE=$BASE_IMAGE"
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username buildessential --password-stdin
      - name: Push image to Docker Hub
        run: |
          docker push "buildessential/$OS:$RELEASE"
          if [ "$RELEASE" = "buster" ] || [ "$RELEASE" = "focal" ]; then
            docker tag "buildessential/$OS:$RELEASE" "buildessential/$OS:latest"
            docker push "buildessential/$OS:latest"
          fi
